apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      role: msvc-postgres
  template:
    metadata:
      labels:
        role: msvc-postgres
    spec:
      containers:
        - name: msvc-postgres
          image: postgres:12-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: root
            - name: POSTGRES_DB
              value: db_springboot_cloud