apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-oauth
spec:
  replicas: 1
  selector:
    matchLabels:
      role: msvc-oauth
  template:
    metadata:
      labels:
        role: msvc-oauth
    spec:
      containers:
        - name: msvc-oauth
          image: damiang6666/msvc-oauth:latest
          ports:
            - containerPort: 9001
---
apiVersion: v1
kind: Service
metadata:
  name: msvc-oauth
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9001